_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 17
                - 19
                - 23
                - 55
            "4": 3.9.18
            "5": 0.18.1
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
batch_size:
    value: 32
dropout:
    value: 0.5
epochs:
    value: 300
image_size:
    value: 128
k1:
    value: 0.2
k2:
    value: 0.6
learning_rate:
    value: 0.01
num_layers:
    value: 4
prop_pos:
    value: 0.25
run_id:
    value: 2hm8ua1o
search_method:
    value: EB
