wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5
epochs:
  value: 300
image_size:
  value: 128
k1:
  value: 0.2
k2:
  value: 0.6
learning_rate:
  value: 0.01
num_layers:
  value: 4
prop_pos:
  value: 0.25
search_method:
  value: EB
