wandb_version: 1

batch_size:
  value: 16
dropout:
  value: 0.5
epochs:
  value: 300
image_size:
  value: 128
k1:
  value: 0.3
k2:
  value: 0.7
learning_rate:
  value: 0.01
num_layers:
  value: 4
prop_pos:
  value: 0.5
search_method:
  value: EB
